### ISSUE TITLE
`@supports` query breaks highlighting

### ISSUE THREAD

**Issue by chaance** [jacobcassidy/vscode-css-nesting-syntax-highlighting#4]
Video for reference:

https://github.com/user-attachments/assets/d761dba7-c362-4417-b1ce-78965f52f575

Minimal code-block to reproduce:

```css
:root {
	--supports-red: false;
	@supports (color: red) {
		--supports-red: true;
	}
	--x: 1;
}
```

Specs:
- macOS Sonoma 14.7.1
- VS Code 1.96.2
- CSS Nesting Syntax Highlighting: latest (0.1.1 at time of writing)

I've tried disabling all other CSS extensions to ensure no conflicts but can't ID any other culprit 🤔
